### ISSUE TITLE
Disabling of keys

### ISSUE THREAD

**Issue by VarusXX** [VORPCORE/vorp_character-lua#101]
Hi Team!
It is more a request than really a bug. Is it possible to prevent using the mousewheel in charactercreation? We have users which think to scroll through the menu. At the end he uses ESC and the menu is closing, so that he could not create a character and he has to log out and in again

**Comment by outsider31000** [comment]
pressing esc does not remove the menu it only hides, once you get off pause menu, the character creation menu is visible again, but thats for your report ill look at it.

**Comment by bganderson** [comment]
@VarusXX 

There's probably a better way to do this, but this is what I did to hook `INPUT_INSPECT_ZOOM` since I wanted to use mouse scroll instead of `MOUSE1/2` for zooming (modified for your needs). This code will make `ESC` reset the camera and will also will work just as `BACKSPACE` does in navigating the menu. 

Go into `client/createCharacter.lua`;

At the end of `function RegisterGenderPrompt()` add:
```lua
str = "reset camera" -- OR str = T.PromptLabels.promptresetCam and define it in shared/translations.lua
resetcam = PromptRegisterBegin()
PromptSetControlAction(resetcam, `INPUT_FRONTEND_CANCEL`)
str = CreateVarString(10, 'LITERAL_STRING', str)
PromptSetText(resetcam, str)
PromptSetEnabled(resetcam, 0)
PromptSetVisible(resetcam, 0)
PromptSetStandardMode(resetcam, 0)
PromptSetGroup(resetcam, PromptGroup2)
PromptRegisterEnd(resetcam)
```

Inside `function StartPrompts(value)` at the end of `while IsInCharCreation or IsInClothingStore do` add:
```lua
if IsControlPressed(2, `INPUT_FRONTEND_CANCEL`) then
	-- reset camera
	SetCamCoord(cam, -560.1333, -3780.923, 238.98)
	SetCamFov(cam, 55.00)
end 
```

And finally at the end of `function EnableCharCreationPrompts(boolean)` add:
```lua
PromptSetEnabled(resetcam, boolean)
PromptSetVisible(resetcam, boolean)
```

Keep in mind, if you manually modify these files, the changes will be overwritten when you pull from master or install the latest version of `vorp_characters`, maintaining your own fork can get frustrating and sometimes messy.
