### ISSUE TITLE
Character Selection Menu Wont Load.

### ISSUE THREAD

**Issue by vlPsychosis** [VORPCORE/vorp_character-lua#120]
**Describe the issue**
I updated Vorp Core, Vorp Inventory, Vorp Character, Vorp Admin, and Vorp Menu. However, now when I load into my server, It just loads me in and does not send me to the character selection menu first. When I check, Vorp says everything is up to date. And I'm rather new to this so I've been struggling to find what the issue is.

**Expected behavior**
I expected to load the server, and be brought to my character selection menu. However, it just loads me in on the character I was last on prior to updating the files.

**Screenshots**
![image](https://github.com/VORPCORE/vorp_character-lua/assets/143574041/bdeaa746-b8d1-4403-abb1-1f533ca3486b)

![image](https://github.com/VORPCORE/vorp_character-lua/assets/143574041/5ce0dc4d-8524-44e1-a167-f6bbbea043b8)

**Comment by bganderson** [comment]
This is caused by a schema problem in the `characters` table which prevents your character from getting saved. The error says the `joblabel` field is missing. You can confirm this by running this query against the database; `DESCRIBE vorpv2.characters` (replace `vorpv2` with whatever your database name is). 

You should be able to patch it by modifying your `characters` table to match the one in their pre-made [MariaDB.sql](https://github.com/VORPCORE/vorp_pre-made/blob/main/MariaDB.sql). From what I saw when I looked, it will need more modifications than just that `joblabel` field. 

I believe this is actually an issue in `vorp_core` since I'm pretty sure that resource creates the `characters` table.

**Comment by outsider31000** [comment]
yes job label is missing not a vorp character issue. 
ALTER TABLE characters ADD COLUMN joblabel VARCHAR(255) DEFAULT 'job label' AFTER job; you can run this code.

any other issues open them i ntheir respective repos. or ask in discord.
